# help/en/overview.ftl — Vikunja help texts (English)

help-vikunja-title = Vikunja — Open-Source Task Management

help-vikunja-body =
    Vikunja is an open-source task management and to-do list application.
    It provides the task tracking and project management layer of the
    FreeSynergy platform.

    Features:
    - Multiple views: List, Kanban board, Gantt chart, calendar
    - Projects (formerly "Namespaces") with nested tasks and subtasks
    - Due dates, reminders, priorities and labels
    - Task assignments (assign tasks to team members)
    - Recurring tasks
    - File attachments
    - Team workspaces with granular permissions
    - API for automation and integrations
    - OIDC / SSO authentication via Kanidm
    - Email reminders (via Stalwart or any SMTP server)

    Dependencies: PostgreSQL (task data), Dragonfly (caching, Redis DB 3),
    Kanidm (SSO), optionally Stalwart (email reminders).

    Constraint: per_host = 1, per_ip = 1.

help-vikunja-install-title = Installing Vikunja

help-vikunja-install-body =
    1. Before installing, create an OAuth2 client in Kanidm:
       - Client name: "vikunja"
       - Redirect URI: https://tasks.example.com/auth/openid/vikunja
       - Scopes: openid, email, profile
       - Note the client secret.

    2. Run the setup wizard:
       - Service domain (e.g. tasks.example.com)
       - JWT secret (auto-generated)
       - Database password (auto-generated)

    3. Configure OIDC in config.yml (generated by the deploy-setup hook):
         auth:
           openid:
             enabled: true
             providers:
               - name: "Kanidm"
                 authurl: "https://auth.example.com/oauth2/openid/vikunja"
                 clientid: "vikunja"
                 clientsecret: "<from-kanidm>"

    4. After first start, any user who logs in via OIDC can create tasks.
       The first OIDC user does NOT automatically become admin —
       promote them via the admin API or set local auth temporarily.

    5. To make a user admin:
         podman exec {instance_name} /app/vikunja/vikunja user set-admin <username>

help-vikunja-oidc-title = OIDC and Authentication

help-vikunja-oidc-body =
    Vikunja supports two authentication modes:

    OIDC (recommended): Users sign in through Kanidm (or any OIDC provider).
    No local passwords needed. Controlled by:
        VIKUNJA_AUTH_OPENID_ENABLED = "true"

    Local: Users have a username/password stored in Vikunja's database.
    Can coexist with OIDC. Controlled by:
        VIKUNJA_AUTH_LOCAL_ENABLED = "true"/"false"

    For FreeSynergy deployments, the recommended setup is:
    - OIDC: enabled (Kanidm as provider)
    - Local auth: disabled (VIKUNJA_AUTH_LOCAL_ENABLED = "false")

    This forces all users to authenticate through Kanidm, ensuring a single
    identity across the platform. The admin can still use the CLI to manage
    users without a password.

    Note: Vikunja's OIDC configuration is in config.yml (not env vars).
    The deploy-setup hook generates this file from the project configuration.

help-vikunja-mail-title = Email Reminders

help-vikunja-mail-body =
    Vikunja sends emails for:
    - Task reminders (due date notifications)
    - Team invitation emails
    - Mention notifications

    Configuration:
        VIKUNJA_MAILER_ENABLED:   "true" to enable
        VIKUNJA_MAILER_HOST:      SMTP server (e.g. Stalwart container name)
        VIKUNJA_MAILER_PORT:      587 (STARTTLS) or 465 (implicit TLS)
        VIKUNJA_MAILER_USERNAME:  SMTP auth username
        VIKUNJA_MAILER_PASSWORD:  SMTP password (stored in vault)
        VIKUNJA_MAILER_FROMEMAIL: sender address (e.g. tasks@example.com)

    With Stalwart: set HOST to the Stalwart container name, PORT to 587.
    Create a dedicated mailbox in Stalwart for the tasks sender address.

    Reminders are scheduled based on VIKUNJA_SERVICE_TIMEZONE. Make sure
    this matches the timezone of your users for accurate reminder delivery.
