# help/en/fields.ftl — Outline field help texts (English)

help-outline-field-secret-key-title = Secret Keys (SECRET_KEY / UTILS_SECRET)

help-outline-field-secret-key-body =
    Outline requires two separate secret keys:

    SECRET_KEY: Signs authentication cookies and session tokens. Must be at
    least 32 random characters. Auto-generated and stored in vault.

    UTILS_SECRET: Used for signing internal utility requests such as file
    export links and scheduled job tokens. Also auto-generated.

    Important: Keep both keys stable. Rotating SECRET_KEY invalidates all
    active user sessions — everyone gets logged out. Rotating UTILS_SECRET
    invalidates any in-flight export or scheduled operations.

    Never set these to short, guessable, or static values. The auto-generated
    64-character hex strings provide more than sufficient entropy.

help-outline-field-oidc-title = OIDC Client Credentials

help-outline-field-oidc-body =
    Outline uses OIDC (OpenID Connect) for user authentication via Kanidm.

    OIDC_CLIENT_ID: The OAuth2 client name registered in Kanidm (default: "outline").
    Must exactly match the client name in Kanidm — case-sensitive.

    OIDC_CLIENT_SECRET: The client secret generated by Kanidm when registering
    the "outline" OAuth2 application. Stored in vault.

    OIDC_AUTH_URI, OIDC_TOKEN_URI, OIDC_USERINFO_URI, OIDC_LOGOUT_URI:
    These are automatically derived from the Kanidm service domain. They point to:
        https://<kanidm_domain>/ui/oauth2
        https://<kanidm_domain>/oauth2/token
        https://<kanidm_domain>/oauth2/openid/outline/userinfo
        https://<kanidm_domain>/ui/logout

    OIDC_USERNAME_CLAIM: "preferred_username" maps to the Kanidm username.
    Change to "email" if you prefer email addresses as Outline display names.

    OIDC_DISPLAY_NAME: The label on the "Sign in with …" button. Set to your
    organization name or "Kanidm" for clarity.

help-outline-field-upload-size-title = Max Upload Size

help-outline-field-upload-size-body =
    FILE_STORAGE_UPLOAD_MAX_SIZE controls the maximum size of any single file
    upload (images, attachments, etc.) in bytes.

    Default: 262144000 bytes = 250 MB

    Adjust based on your team's needs:
    - 52428800  =  50 MB (conservative, mostly text documents)
    - 262144000 = 250 MB (default, suitable for most teams)
    - 524288000 = 500 MB (for teams sharing large design files or videos)

    Note: Large uploads also require sufficient disk space on the storage volume
    and Zentinel's request body size limit (client_max_body_size in nginx terms)
    to be set to at least the same value.

help-outline-field-language-title = Default Language

help-outline-field-language-body =
    DEFAULT_LANGUAGE sets the UI language for new users on first login.
    Outline supports many locales — use the standard locale code format.

    Common values:
    - en_US: English (United States) — default
    - de_DE: German (Germany)
    - fr_FR: French (France)
    - es_ES: Spanish (Spain)
    - ja_JP: Japanese (Japan)

    Individual users can override this in their profile settings.
    The admin can also set a default in the workspace settings.

help-outline-field-db-pool-title = Database Connection Pool

help-outline-field-db-pool-body =
    DATABASE_CONNECTION_POOL_MIN: Minimum idle connections kept open.
    DATABASE_CONNECTION_POOL_MAX: Maximum connections the pool may open.

    Both default to empty string (Outline uses its internal defaults: min=1, max=5).

    When to adjust:
    - High traffic (50+ active users): increase max to 10–20
    - Memory-constrained host: reduce max to 2–3
    - Fast response requirements: increase min so connections are pre-warmed

    Never set max higher than PostgreSQL's max_connections setting (check with:
        podman exec {postgres_container} psql -U {user} -c "SHOW max_connections;"
    )
    PostgreSQL reserves 3 connections for superuser operations, so the effective
    limit is max_connections - 3 shared across all applications.
