// Catalog<M> — generic package catalog and related types.
//
// Design pattern: generic container (Catalog<M>) + project-supplied element
// type (M). The catalog handles lookup and filtering; the element type carries
// all project-specific fields.
//
// catalog.toml structure (per namespace):
//
//   [catalog]          ← CatalogMeta (informational)
//   [[packages]]       ← Vec<M>  (project-supplied type)
//   [[locales]]        ← Vec<LocaleEntry>

use serde::{Deserialize, Serialize};

use crate::manifest::Manifest;

// ── CatalogMeta ───────────────────────────────────────────────────────────────

/// The `[catalog]` header block — auto-generated by CI, informational only.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct CatalogMeta {
    #[serde(default)]
    pub project: String,
    #[serde(default)]
    pub version: String,
    #[serde(default)]
    pub generated_at: String,
}

// ── Catalog<M> ────────────────────────────────────────────────────────────────

/// Generic catalog for any package type `M`.
///
/// Deserializes the `[[packages]]` and `[[locales]]` arrays from a
/// `catalog.toml` file. Projects supply their own `M` type (e.g.
/// `ModuleManifest` for FSN, `PluginManifest` for Wiki.rs).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Catalog<M> {
    /// Catalog metadata — informational, safe to ignore.
    #[serde(default)]
    pub catalog: CatalogMeta,

    /// All packages listed in this catalog.
    #[serde(default = "Vec::new")]
    pub packages: Vec<M>,

    /// All available locale packs listed in this catalog.
    #[serde(default)]
    pub locales: Vec<LocaleEntry>,
}

impl<M> Default for Catalog<M> {
    fn default() -> Self {
        Self { catalog: CatalogMeta::default(), packages: Vec::new(), locales: Vec::new() }
    }
}

impl<M> Catalog<M> {
    /// Parse a catalog from a TOML string.
    pub fn from_toml(s: &str) -> anyhow::Result<Self>
    where
        M: for<'de> Deserialize<'de>,
    {
        toml::from_str(s).map_err(|e| anyhow::anyhow!("catalog parse error: {e}"))
    }

    /// Filter packages by category prefix.
    ///
    /// `"deploy."` matches `"deploy.proxy"`, `"deploy.iam"`, etc.
    pub fn by_category<'a>(&'a self, prefix: &str) -> Vec<&'a M>
    where
        M: Manifest,
    {
        self.packages.iter()
            .filter(|p| p.category().starts_with(prefix))
            .collect()
    }

    /// Find a package by exact ID.
    pub fn find(&self, id: &str) -> Option<&M>
    where
        M: Manifest,
    {
        self.packages.iter().find(|p| p.id() == id)
    }
}

// ── LocaleEntry ───────────────────────────────────────────────────────────────

/// One locale entry in `[[locales]]`.
///
/// Shared across all namespaces — locale metadata is always the same shape.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LocaleEntry {
    /// BCP-47 locale code, e.g. "de", "ar", "pt-br".
    pub code: String,

    /// Display name in the locale's own script, e.g. "Deutsch", "العربية".
    pub name: String,

    /// Version string (semver).
    #[serde(default = "default_version")]
    pub version: String,

    /// Percentage of keys translated, 0–100. Updated by CI.
    #[serde(default)]
    pub completeness: u8,

    /// Text direction: "ltr" or "rtl".
    #[serde(default = "default_direction")]
    pub direction: String,

    /// Translation API version — must match `TRANSLATION_API_VERSION` in the app.
    #[serde(default = "default_api_version")]
    pub api_version: u32,

    /// Store-relative path to the locale directory, e.g. "Node/i18n/de".
    #[serde(default)]
    pub path: Option<String>,
}

impl LocaleEntry {
    /// Returns the path to `ui.toml` within a resolved store root.
    pub fn ui_toml_path(&self, store_root: &std::path::Path) -> Option<std::path::PathBuf> {
        self.path.as_ref().map(|p| store_root.join(p).join("ui.toml"))
    }
}

fn default_version()   -> String { "1.0.0".into() }
fn default_direction() -> String { "ltr".into() }
fn default_api_version() -> u32  { 1 }
