// store-sdk — FreeSynergy Store generic catalog, i18n and client SDK.
//
// This crate is project-agnostic. It knows nothing about FSN modules,
// Wiki.rs plugins, or any other FreeSynergy project. Projects depend on
// this crate and supply their own manifest types.
//
// Public API:
//   Manifest trait          — implement on your package entry type
//   PackageMeta             — the [package] block in manifest.toml
//   Catalog<M>              — generic catalog container with filtering helpers
//   CatalogMeta             — the [catalog] header block (auto-generated by CI)
//   LocaleEntry             — one [[locales]] entry in catalog.toml
//   StoreSource             — where data comes from (LocalPath / RemoteHttp)
//   StoreClient             — fetch catalog + load i18n from a StoreSource
//   I18nBundle              — loaded locale data (meta + ui.toml)
//   I18nMeta                — [i18n] block from locale manifest.toml
//   TextDirection           — Ltr / Rtl

pub mod catalog;
pub mod client;
pub mod i18n;
pub mod manifest;

// ── Flat re-exports ───────────────────────────────────────────────────────────

pub use catalog::{Catalog, CatalogMeta, LocaleEntry};
pub use client::{StoreClient, StoreSource};
pub use i18n::{I18nBundle, I18nMeta, TextDirection};
pub use manifest::{Manifest, PackageCompat, PackageMeta, PackageSource};
