# help/en/fields.ftl — PostgreSQL field help texts (English)

help-postgres-field-db-name-title = Database Name (POSTGRES_DB)

help-postgres-field-db-name-body =
    The name of the database created by initdb on first start. Defaults to the
    parent service's instance name (e.g. "forgejo" for a Forgejo deployment).

    The parent service's DATABASE_URL or equivalent is automatically derived
    from this value. Change it only if your parent service requires a specific
    database name that differs from the instance name.

    This value cannot be changed after the database has been created without
    recreating the cluster from scratch.

help-postgres-field-db-user-title = Database User (POSTGRES_USER)

help-postgres-field-db-user-body =
    The superuser account created by initdb. Defaults to the parent service's
    instance name. The parent service connects to PostgreSQL using this user.

    This user has full superuser privileges on the cluster. Do not use it for
    application connections in production if you want stricter separation —
    create a separate role via an init script. For FreeSynergy deployments
    the default setup is safe as each service gets its own isolated container.

help-postgres-field-db-password-title = Database Password (POSTGRES_PASSWORD)

help-postgres-field-db-password-body =
    Password for the database superuser. Auto-generated by the setup wizard and
    stored in the vault. The parent service retrieves this value from the vault
    at deploy time and injects it into its DATABASE_URL.

    Never set this to a static or empty value in production. The auto-generated
    password is a 32-character random string — sufficient for all use cases.

help-postgres-field-auth-method-title = Authentication Method (POSTGRES_HOST_AUTH_METHOD)

help-postgres-field-auth-method-body =
    Controls how client connections must authenticate. The default "scram-sha-256"
    is the current best practice — passwords are verified using a challenge-response
    mechanism that never sends the password in cleartext.

    Do not change this to "md5" (older, weaker hashing) or "trust" (no password
    required) in production. Both reduce security significantly.

    The POSTGRES_INITDB_ARGS variable passes "--auth-host=scram-sha-256" to initdb,
    which enforces this method cluster-wide from the very first start.

help-postgres-field-locality-title = Locality Constraint (same_host)

help-postgres-field-locality-body =
    PostgreSQL has a "same_host" locality constraint, which means FreeSynergy
    will always place it on the same physical machine as the service that depends on it.

    This is required for performance and simplicity — the database connects over
    the Podman internal network (not over the internet), and latency must be minimal.

    If you need to run PostgreSQL on a separate host, you must configure an
    external DATABASE_URL in the parent service and remove the Postgres sub-module
    dependency from your project file.
