# help/en/fields.ftl — Kanidm field help texts (English)

help-kanidm-field-domain-title = Service Domain

help-kanidm-field-domain-body =
    The public domain name for this Kanidm instance (e.g. auth.example.com).
    This becomes the issuer URL for all OIDC tokens:
        https://auth.example.com/oauth2/openid/<client-id>

    Important: This value is baked into Kanidm's database on first start and
    cannot be changed without a full reinstall. Choose the domain carefully
    before deploying.

    All services that use Kanidm for SSO will reference this domain in their
    OIDC configuration.

help-kanidm-field-admin-password-title = Admin Password

help-kanidm-field-admin-password-body =
    The initial password for the built-in "admin" account. Auto-generated by
    the setup wizard and stored in the vault.

    Use this password only for the first login to bootstrap Kanidm. After
    logging in, create a named admin account and disable or revoke the
    "admin" account's elevated privileges.

    The "idm_admin" account (separate from "admin") manages identity objects
    like users, groups and OAuth2 clients. Use idm_admin for day-to-day
    administration.

help-kanidm-field-federation-title = Federation Trust Level

help-kanidm-field-federation-body =
    The minimum federation trust level required for other FreeSynergy nodes to
    use this Kanidm instance as an identity provider.

    Trust levels:
    0 — No federation (local only)
    1 — Basic federation (read access to profile data)
    2 — Full federation (SSO across federated projects)

    The default (min_trust = 1) allows federated nodes to verify identities
    but not create sessions. Raise to 2 only for nodes you fully trust.
