# help/en/fields.ftl — Dragonfly field help texts (English)

help-dragonfly-field-password-title = Cache Password (DFLY_requirepass)

help-dragonfly-field-password-body =
    Password required for all client connections to Dragonfly. Auto-generated by
    the setup wizard and stored in the vault as "vault_cache_password".

    All services that use Dragonfly (Forgejo, Outline, Vikunja, uMap, pretix)
    retrieve this password from the vault and inject it into their Redis URL:
        redis://:{password}@{container_name}:{port}/{db}

    Never leave this empty in production. An unprotected Dragonfly instance can
    be accessed by any process in the same Podman network.

help-dragonfly-field-maxmemory-title = Memory Limit (DFLY_maxmemory)

help-dragonfly-field-maxmemory-body =
    Maximum memory Dragonfly may use before evicting entries.
    Accepts size suffixes: mb (megabytes), gb (gigabytes).

    Default: 2gb — suitable for a small server with 3–5 services.

    Sizing guidelines:
    - 1gb: minimal setup (1–2 services, small caches)
    - 2gb: standard setup (3–5 services)
    - 4gb: larger setups with heavy caching or active job queues

    Set to roughly 60–70% of available RAM minus the memory used by other
    containers. Dragonfly's actual memory footprint is typically 30–40% lower
    than Redis for equivalent datasets.

    When this limit is reached:
    - If DFLY_cache_mode = "true": LRU eviction (older entries removed)
    - If DFLY_cache_mode = "false": new writes fail with an error

help-dragonfly-field-cache-mode-title = Cache Eviction Mode (DFLY_cache_mode)

help-dragonfly-field-cache-mode-body =
    Controls behavior when maxmemory is reached.

    "false" (default): Dragonfly returns an error when memory is full. Services
    may fail to cache new entries but retain existing cached data.

    "true": Dragonfly evicts the least-recently-used (LRU) entries to make room
    for new ones. Data loss is possible but the service stays functional.

    For FreeSynergy use cases (session caches, job queues), "false" is typically
    safer — if the cache fills up, it signals that maxmemory should be increased,
    rather than silently discarding session data.

    Use "true" only if all data in Dragonfly is truly disposable cache (nothing
    that would break service functionality if lost).

help-dragonfly-field-persistence-title = Persistence (DFLY_dbfilename / DFLY_dir)

help-dragonfly-field-persistence-body =
    DFLY_dbfilename: filename for RDB snapshots (e.g. dump.rdb).
    DFLY_dir: directory to write snapshots to (must be a mounted volume path).

    Both default to empty string — persistence disabled.

    When persistence is disabled:
    - All data is lost on container restart
    - This is intentional for cache-only deployments
    - Services automatically re-populate their caches on reconnect

    To enable persistence, set both variables and mount a volume:
        DFLY_dbfilename = "dump.rdb"
        DFLY_dir = "/data"
    Then add a volume mount: /path/on/host:/data

    Note: Enabling persistence does NOT eliminate data loss risk — it only
    reduces the window. For truly persistent data, use PostgreSQL.

help-dragonfly-field-threads-title = Worker Threads (DFLY_proactor_threads)

help-dragonfly-field-threads-body =
    Number of I/O threads in Dragonfly's proactor engine.

    0 (default): Dragonfly auto-detects the number of available CPU cores and
    uses one thread per core. This is the recommended setting for most deployments.

    Set to a specific number (e.g. 4) to limit CPU usage on a shared host where
    you don't want Dragonfly to consume all available cores.

    Unlike Redis (single-threaded), Dragonfly scales linearly with CPU cores.
    For CPU-intensive workloads (large Lua scripts, many concurrent connections),
    allowing full auto-detection gives the best performance.
