# help/en/overview.ftl — CryptPad help texts (English)

help-cryptpad-title = CryptPad — End-to-End Encrypted Collaboration

help-cryptpad-body =
    CryptPad is an end-to-end encrypted collaborative office suite. All documents
    are encrypted in the browser before being sent to the server — the server never
    sees the plaintext content of any document.

    Applications included:
    - Rich text documents (like Google Docs)
    - Spreadsheets
    - Kanban boards
    - Code editors with syntax highlighting
    - Presentations (slideshows)
    - Whiteboards
    - Forms and surveys
    - Markdown documents

    CryptPad requires TWO domains to operate securely:
    1. Main domain (e.g. pad.example.com) — for the CryptPad UI
    2. Sandbox domain (e.g. sandbox.example.com or sandbox.pad.example.com)
       — isolated origin for rendering document content safely

    Both domains must have Zentinel proxy routes configured.

    Dependencies: Kanidm (SSO/authentication).

help-cryptpad-install-title = Installing CryptPad

help-cryptpad-install-body =
    1. Choose two domains:
       - Main: pad.example.com
       - Sandbox: sandbox.example.com (or sandbox.pad.example.com)
       Both must be separate DNS entries pointing to the same server.

    2. Add both routes in the Zentinel contract:
       - Route "main": pad.example.com → container:3000
       - Route "sandbox": sandbox.example.com → container:3000

    3. Run the setup wizard:
       - CPAD_MAIN_DOMAIN: https://pad.example.com
       - CPAD_SANDBOX_DOMAIN: https://sandbox.example.com
       - Admin email: your address (shown in CryptPad footer)

    4. After first start, log in with any account. To become an admin, open
       the browser console at https://pad.example.com and get your public key:
         CryptPad.getPublicKey()
       Then add it to the admin list in config.js.

    5. SSO via Kanidm is configured in CryptPad's SSO plugin (see OIDC topic).

help-cryptpad-sandbox-title = The Sandbox Domain

help-cryptpad-sandbox-body =
    CryptPad uses a separate sandbox domain as a security measure. When you
    open a document, CryptPad renders it inside an <iframe> loaded from the
    sandbox domain. This provides origin isolation:

    - Documents cannot access cookies or localStorage of the main domain
    - JavaScript in documents cannot make requests to the main domain
    - Content Security Policy (CSP) is enforced independently per origin

    This is what makes CryptPad safe to use even if a document contains
    malicious JavaScript — it's sandboxed in a completely separate origin.

    The sandbox domain must:
    - Be a different origin (different domain or subdomain) from the main domain
    - Be reachable via HTTPS
    - Have a Zentinel proxy route pointing to the same CryptPad container

    Important: CPAD_SANDBOX_DOMAIN must match exactly what clients see in the
    browser — including the scheme (https://). A mismatch will break document
    rendering.

help-cryptpad-oidc-title = OIDC / SSO with Kanidm

help-cryptpad-oidc-body =
    CryptPad supports OIDC via its SSO plugin. Configuration is done in the
    server-side config.js file (not in environment variables).

    Steps:
    1. In Kanidm, create an OAuth2 client named "cryptpad":
       - Redirect URI: https://pad.example.com/login/sso/callback
       - Scopes: openid, email, profile
    2. In CryptPad's config.js (generated by the deploy-setup hook):
         sso: {
           list: [{
             name: "Kanidm",
             type: "oidc",
             url: "https://auth.example.com/oauth2/openid/cryptpad",
             clientId: "cryptpad",
             clientSecret: "<from-kanidm>"
           }]
         }
    3. Restart the CryptPad container.

    Users will see a "Login with Kanidm" button on the CryptPad login page.
    Their CryptPad account is linked to their Kanidm identity.
