# help/en/fields.ftl — Stalwart field help texts (English)

help-stalwart-field-hostname-title = Server Hostname (STALWART_HOSTNAME)

help-stalwart-field-hostname-body =
    The fully qualified domain name (FQDN) of this mail server.
    Used only during first-start initialization for:
    - The EHLO/HELO greeting sent to other mail servers
    - The TLS certificate domain (Stalwart auto-provisions via ACME)
    - The default from-domain for system-generated messages

    Example: mail.example.com

    This should be a subdomain of your main domain with a valid A record
    pointing to the server's IP address. Other mail servers will do a reverse
    DNS lookup on your IP — the PTR record should match this hostname.

    After first start, this value can be updated in the Web Admin UI.

help-stalwart-field-domains-title = Email Domains (STALWART_DOMAINS)

help-stalwart-field-domains-body =
    Comma-separated list of email domains this server accepts mail for.
    Used only during first-start initialization.

    Example: example.com,example.org

    After initialization, additional domains can be added in the Web Admin UI
    under Settings > Domains. Each domain needs its own MX, SPF and DKIM
    DNS records.

    The domains listed here are the ones for which Stalwart creates mailboxes.
    Transactional services (Forgejo, Vikunja, etc.) typically send from addresses
    like noreply@example.com — these need to be registered as domains here.

help-stalwart-field-admin-password-title = Admin Password

help-stalwart-field-admin-password-body =
    Password for the built-in "admin" account in the Stalwart Web Admin UI.
    Auto-generated by the setup wizard and stored in the vault.

    The Web Admin UI is accessible at: https://{service_domain}/admin

    Use this account to:
    - Configure DKIM signing keys
    - Set up OIDC authentication
    - Create and manage mailboxes
    - Monitor mail queues and spam scores
    - View delivery logs

    Tip: After setting up OIDC, create a second admin account linked to your
    Kanidm identity. Keep the local "admin" account as a recovery option.
